# Use case configuration for Fairphone 4
# Author: Luca Weiss <luca.weiss@fairphone.com>

Syntax 4

SectionUseCase."HiFi" {
	File "/Fairphone/fp4/HiFi.conf"
	Comment "HiFi quality Music."
}

BootSequence [
	cset "name='ADC1 Volume' 12"
]

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
Include.wcd-init.File "/codecs/wcd938x/init.conf"
Include.rxm-init.File "/codecs/qcom-lpass/rx-macro/init.conf"
